name: CI
on:
  schedule:
    # Every five minutes (maximum frequency allowed by GitHub)
    - cron: "0 * * * *"

permissions:
  contents: write

jobs:
  aggregate:
    name: Aggregate Dependencies
    runs-on: ubuntu-latest
    env:
      CARGO_VET_VERSION: 0.9.0
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Binstall
        uses: cargo-bins/cargo-binstall@main

      - name: Install Vet
        run: cargo binstall cargo-vet

      - name: Aggregate
        run: cargo vet aggregate --output-file audits.toml sources.list

      - name: Commit changes (if any)
        run: |
          git config --global user.name "cargo-vet[bot]"
          git config --global user.email "cargo-vet-aggregate@invalid"
          git add audits.toml
          git commit -m "Aggregate new audits" || true

      - name: Push changes (if any)
        run: git push origin main
